### ISSUE TITLE
Data models for Django + DB

### ISSUE THREAD

**Issue by raymondaing** [family-news-feed/python-api#10]
Initialize DB tables through Django models.
Two files per model; one for model definition and one for model methods/functionality (if possible).
This can be broken up as models folder and managers folder.
Tables:
![FamilyNewsFeedDiagrams-Data Model](https://user-images.githubusercontent.com/36826379/107570393-702b3880-6bb7-11eb-8e03-f4f83f3164f2.png)

**Comment by benjamindburke** [comment]
Merged and fixed.
