### ISSUE TITLE
Setting Initial History / Initial Changelog

### ISSUE THREAD

**Issue by benjamindburke** [family-news-feed/python-api#32]
When a CREATE statement is being made for a patient or a guardian, I.E. this is the patient's first entry into the system with the MRN, this should always result in an initial SMS message being delivered to the phone. This initial version from the PFMT becomes the historical reference in the database table and is referred to for all future notifications.

**Comment by raymondaing** [comment]
On new patient, we send out a notification stating the current status of the patient.
